version: "3"
services:
  mysql:
    hostname: mysqldb
    image: mysql:8.0.26
    volumes:
      - mysql-storage:/var/lib/mysql
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: lake
      MYSQL_USER: merico
      MYSQL_PASSWORD: merico
    networks:
      - lake
  grafana:
    hostname: grafana
    image: grafana/grafana:8.0.6
    ports:
      - 3002:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/img/grafana_icon.svg:/usr/share/grafana/public/img/grafana_icon.svg:rw
      - ./grafana/img:/usr/share/grafana/public/img/lake:ro
    env_file:
      - ./grafana/grafana.config
    restart: always
    networks:
      - lake
    depends_on:
      - mysql
  devlake:
    image: mericodev/lake:latest
    ports:
      - 127.0.0.1:8080:8080
    env_file:
      - ./.env
    restart: always
    networks:
      - lake
    depends_on:
      - grafana
volumes:
  mysql-storage:
  grafana-storage:
networks:
  lake:
