version: "3"
services:
  mysql:
    image: mysql:8.0.26
    platform: linux/x86_64
    volumes:
      - mysql-storage:/var/lib/mysql
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: lake
      MYSQL_USER: merico
      MYSQL_PASSWORD: merico
  grafana:
    image: grafana/grafana:8.0.6
    ports:
      - 3002:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/img/grafana_icon.svg:/usr/share/grafana/public/img/grafana_icon.svg:rw
      - ./grafana/img:/usr/share/grafana/public/img/lake:ro
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DASHBOARDS_JSON_ENABLED=true
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - GF_LIVE_ALLOWED_ORIGINS=*
    restart: always
    depends_on:
      - mysql
  devlake:
    image: mericodev/lake
    ports:
      - 127.0.0.1:8080:8080
    env_file:
      - ./.env
    restart: always
    depends_on:
      - grafana
  config-ui:
    image: mericodev/config-ui
    ports:
      - 127.0.0.1:4000:80
    env_file:
      - ./.env
    environment:
      - ENV_FILEPATH=/.env
    volumes:
      - ./.env:/.env:rw
volumes:
  mysql-storage:
  grafana-storage:
