# config file version
apiVersion: 1

datasources:
  - name: mysql
    type: mysql
    url: mysqldb:3306
    database: lake
    user: merico
    secureJsonData:
      password: "merico"
    editable: true
